version: '3'
services:
  node:
    container_name: discord-bot
    build:
      context: .
      dockerfile: build/node/Dockerfile
    volumes:
      - ./:/home/node/app
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      LEGISCAN_API_KEY: ${LEGISCAN_API_KEY}
    ulimits:
      nofile:
        soft: 65535
        hard: 100000
